// *************** REGISTER CONSTANTS *************** //
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESSFULL = 'REGISTER_USER_SUCCESSFULL'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'

// *************** LOGIN CONSTANTS *************** //
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_SUCCESSFULL = 'LOGIN_USER_SUCCESSFULL'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'
export const LOGOUT_USER = 'LOGOUT_USER'
